apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rollouts-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ktor-sample
            port:
              number: 80